version: '2.2'
services:
  es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.6.1
    container_name: es
    environment:
      - node.name=es
      - cluster.name=es-kibana-docker-cluster
      - discovery.seed_hosts=es
      - cluster.initial_master_nodes=es,kibana
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - dataes:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - elastic

  kibana:
    image: docker.elastic.co/kibana/kibana:7.6.1
    container_name: kibana
    environment:
      SERVER_HOST: "localhost"
      ELASTICSEARCH_HOSTS: "http://localhost:9200" 
      LOGGING_VERBOSE: "false"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - datakibana:/usr/share/kibana/data
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks:
      - elastic

volumes:
  dataes:
    driver: local
  datakibana:
    driver: local

networks:
  elastic:
    driver: bridge
